# Player Setting
PLAYER_START_X = 0
PLAYER_START_Y = 0
# 1.0x, 1.5x, 2x
PLAYER_VIEW_SIZE = 2
PLAYER_SPEED = 8
PLAYER_DASH_SPEED = 10
PLAYER_SHOOT_COOLDOWN = 20
GUN_OFFSET_X = 45
GUN_OFFSET_Y = 5

# Debug
SHOW_PLAYERHITBOX = True
SHOW_CURRENTFPS = False

# Bullet
BULLET_COOLDOWN = 20
BULLET_VIEWSIZE = 1.4
BULLET_SPEED = 10
BULLET_LIFETIME = 900